### ISSUE TITLE
uf.readBigUInt64LE is not a function

### ISSUE THREAD

**Issue by JohnAlexCO** [drake7707/paintbynumbersgenerator#36]
Full error:
```
pkg cli.js
> pkg@5.6.0
> Targets not specified. Assuming:
  node10-linux-x64, node10-macos-x64, node10-win-x64
> Error! TypeError: buf.readBigUInt64LE is not a function
    at patchCommand (/usr/local/lib/node_modules/pkg/lib-es5/mach-o.js:17:33)
    at patchMachOExecutable (/usr/local/lib/node_modules/pkg/lib-es5/mach-o.js:41:9)
    at exec (/usr/local/lib/node_modules/pkg/lib-es5/index.js:515:63)
```
The program works fine in `node`, and my program doesn't use any special big numbers or the readBigUInt64LE function, so I have no idea why this is happening, but I'm assuming it's something to do with how `pkg` internally represents data.

**Comment by JohnAlexCO** [comment]
I do not know why GitHub decided to put this issue on your project, this was supposed to be left in an entirely different repository. Sorry about that
